"""
Django settings for ydcleaning project.

Generated by 'django-admin startproject' using Django 6.0.3.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""
import os
import dj_database_url
import warnings
from pathlib import Path

import environ

# Load environment variables from a .env file when present (local dev)
env = environ.Env(
    DJANGO_DEBUG=(bool, False),
)
# `.env` read will be performed after `BASE_DIR` is defined further below.

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Read local .env if present
if (BASE_DIR / ".env").exists():
    env.read_env(str(BASE_DIR / ".env"))
if (BASE_DIR / ".env.local").exists():
    env.read_env(str(BASE_DIR / ".env.local"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env.str(
    "DJANGO_SECRET_KEY",
    default="change-me-local",
)

# SECURITY WARNING: don't run with debug turned on in production!
# Use the typed `env` helper for booleans in place of raw os.environ checks.
DEBUG = env.bool("DJANGO_DEBUG", default=False)

# ALLOWED_HOSTS can be provided as a comma-separated string in
# `DJANGO_ALLOWED_HOSTS` or as a list via `ALLOWED_HOSTS`.
_allowed = env.str("DJANGO_ALLOWED_HOSTS", default="")
if _allowed:
    ALLOWED_HOSTS = [h.strip() for h in _allowed.split(",") if h.strip()]
else:
    ALLOWED_HOSTS = env.list( "ALLOWED_HOSTS", default=[ "127.0.0.1", "localhost", ".onrender.com", "ydcleaning.com.au", "www.ydcleaning.com.au", ], )

# Application definition

INSTALLED_APPS = [
    # Django apps
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.sitemaps",
    # My apps
    "core",
    "quotes",
    "services",
    "reviews",
    "gallery",
    "blog",
    "locations",
    "dashboard",
    "google_reviews",
    "customers",
    "bookings",
    "invoices",
    "employees",
    "portal",
    "reports",
    "notifications.apps.NotificationsConfig",
    "contracts",
    "attendance",
    "signatures",
    "payroll",
    "leave_management",
    "rosters",
    "expenses",
    "support",
]
MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "core.middleware.CacheHeaderMiddleware",
    "core.middleware.RoleAccessMiddleware",
    "core.middleware.SEOMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "ydcleaning.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
                "notifications.context_processors.notification_context",
                "dashboard.context_processors.company_settings",
                "dashboard.context_processors.seo_context",
            ],
        },
    },
]

WSGI_APPLICATION = "ydcleaning.wsgi.application"


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

# Support DATABASE_URL for production; default to SQLite for local development
DATABASES = {
    "default": env.db("DATABASE_URL", default=f'sqlite:///{BASE_DIR / "db.sqlite3"}')
}


# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

# Strong password validation
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": (
            "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"
        ),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.MinimumLengthValidator"),
        "OPTIONS": {
            "min_length": 10,
        },
    },
    {
        "NAME": ("django.contrib.auth.password_validation.CommonPasswordValidator"),
    },
    {
        "NAME": ("django.contrib.auth.password_validation.NumericPasswordValidator"),
    },
]

# Customer portal login/logout redirects (single canonical definition)
LOGIN_URL = "/portal/login/"
LOGIN_REDIRECT_URL = "/portal/dashboard/"
LOGOUT_REDIRECT_URL = "/portal/login/"


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "Australia/Adelaide"

USE_I18N = True

USE_TZ = True
SECURE_BROWSER_XSS_FILTER = True
SECURE_CONTENT_TYPE_NOSNIFF = True
SECURE_REFERRER_POLICY = "strict-origin-when-cross-origin"
X_FRAME_OPTIONS = "DENY"

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = "/static/"

STATICFILES_DIRS = [
    BASE_DIR / "static",
]

STATIC_ROOT = BASE_DIR / "staticfiles"

# Use plain static file storage in development so static assets resolve without collectstatic.
if DEBUG:
    STATICFILES_STORAGE = "django.contrib.staticfiles.storage.StaticFilesStorage"
else:
    STATICFILES_STORAGE = env.str(
        "DJANGO_STATICFILES_STORAGE",
        default="whitenoise.storage.CompressedManifestStaticFilesStorage",
    )

MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

# (Email / external keys consolidated later in this file.)

# ====================================================
# Stripe Payment Settings
# Use Stripe test keys first
# ====================================================

STRIPE_SECRET_KEY = env.str("STRIPE_SECRET_KEY", default="")
STRIPE_PUBLISHABLE_KEY = env.str("STRIPE_PUBLISHABLE_KEY", default="")
STRIPE_CURRENCY = env.str("STRIPE_CURRENCY", default="aud")

# (Redirect settings already defined above.)

# Removed plaintext credentials and duplicates; use environment variables.

# ====================================================
# REAL EMAIL SETTINGS - GMAIL SMTP
# Used for quote emails and password reset emails
# ====================================================

EMAIL_BACKEND = env.str(
    "DJANGO_EMAIL_BACKEND",
    default="django.core.mail.backends.smtp.EmailBackend",
)

EMAIL_HOST = env.str("EMAIL_HOST", default="smtp.gmail.com")
EMAIL_PORT = env.int("EMAIL_PORT", default=587)
EMAIL_USE_TLS = env.bool("EMAIL_USE_TLS", default=True)
EMAIL_USE_SSL = env.bool("EMAIL_USE_SSL", default=False)

EMAIL_HOST_USER = env.str("EMAIL_HOST_USER", default="")
EMAIL_HOST_PASSWORD = env.str("EMAIL_HOST_PASSWORD", default="")

if DEBUG and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend" and (
    not EMAIL_HOST_USER or not EMAIL_HOST_PASSWORD
):
    warnings.warn(
        "EMAIL_HOST_USER and/or EMAIL_HOST_PASSWORD are not set. "
        "Falling back to django.core.mail.backends.console.EmailBackend in DEBUG mode.",
        RuntimeWarning,
    )
    EMAIL_BACKEND = "django.core.mail.backends.console.EmailBackend"
    EMAIL_USE_TLS = False
    EMAIL_USE_SSL = False

DEFAULT_FROM_EMAIL = env.str("DEFAULT_FROM_EMAIL", default="")
if EMAIL_HOST_USER and EMAIL_BACKEND == "django.core.mail.backends.smtp.EmailBackend" and EMAIL_HOST == "smtp.gmail.com":
    if not DEFAULT_FROM_EMAIL or "no-reply" in DEFAULT_FROM_EMAIL.lower() or "noreply" in DEFAULT_FROM_EMAIL.lower():
        DEFAULT_FROM_EMAIL = f"YD Commercial Cleaning <{EMAIL_HOST_USER}>"

if not DEFAULT_FROM_EMAIL:
    DEFAULT_FROM_EMAIL = "YD Commercial Cleaning <noreply@localhost>"

ADMIN_EMAIL = env.str("ADMIN_EMAIL", default="")

# ====================================================
# Google OAuth Settings
# ====================================================

GOOGLE_CLIENT_ID = env.str("GOOGLE_CLIENT_ID", default="")
GOOGLE_CLIENT_SECRET = env.str("GOOGLE_CLIENT_SECRET", default="")
GOOGLE_REDIRECT_URI = env.str("GOOGLE_REDIRECT_URI", default="http://localhost:8000/google/oauth/callback/")

# ====================================================
# Resend Email API
# ====================================================

RESEND_API_KEY = env.str("RESEND_API_KEY", default="")

TWILIO_ACCOUNT_SID = env.str("TWILIO_ACCOUNT_SID", default="")
TWILIO_AUTH_TOKEN = env.str("TWILIO_AUTH_TOKEN", default="")
TWILIO_PHONE_NUMBER = env.str("TWILIO_PHONE_NUMBER", default="")

# Security settings (toggleable via env)
SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
SESSION_COOKIE_SECURE = env.bool("SESSION_COOKIE_SECURE", default=False)
CSRF_COOKIE_SECURE = env.bool("CSRF_COOKIE_SECURE", default=False)
SECURE_HSTS_SECONDS = env.int("SECURE_HSTS_SECONDS", default=0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env.bool(
    "SECURE_HSTS_INCLUDE_SUBDOMAINS", default=False
)
SECURE_HSTS_PRELOAD = env.bool("SECURE_HSTS_PRELOAD", default=False)

# Simple logging to surface issues during CI / dev
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "handlers": {"console": {"class": "logging.StreamHandler"}},
    "root": {
        "handlers": ["console"],
        "level": env.str("DJANGO_LOG_LEVEL", default="INFO"),
    },
}

