# Generated by Django 6.0.6 on 2026-10-08 23:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="CleaningGameEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("game_viewed", "Game Viewed"),
                            ("game_started", "Game Started"),
                            ("question_answered", "Question Answered"),
                            ("game_completed", "Game Completed"),
                            ("quote_clicked", "Quote Clicked"),
                        ],
                        db_index=True,
                        max_length=40,
                    ),
                ),
                (
                    "question_number",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("score", models.PositiveSmallIntegerField(blank=True, null=True)),
                (
                    "correct_answers",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                (
                    "total_questions",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("performance_level", models.CharField(blank=True, max_length=40)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["event_type", "created_at"],
                        name="cleaning_ga_event_t_a9de4d_idx",
                    ),
                    models.Index(
                        fields=["question_number", "created_at"],
                        name="cleaning_ga_questio_c5f2d7_idx",
                    ),
                ],
            },
        ),
    ]
