# Generated by Django 6.0.6 on 2026-10-09 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cleaning_game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cleaninggameevent',
            name='is_correct',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaninggameevent',
            name='round_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='cleaninggameevent',
            name='visit_id',
            field=models.UUIDField(blank=True, db_index=True, null=True),
        ),
    ]
