# Generated by Django 6.0.6 on 2026-06-05 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0002_employee_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="hourly_rate",
            field=models.DecimalField(decimal_places=2, default=35, max_digits=8),
        ),
    ]
