# Generated by Django 6.0.6 on 2026-08-25 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0004_employeegoogleaccount"),
    ]

    operations = [
        migrations.AddField(
            model_name="employee",
            name="image",
            field=models.ImageField(
                blank=True,
                help_text="Professional employee photo displayed on the public Team page.",
                null=True,
                upload_to="employees/",
            ),
        ),
    ]
