# Generated by Django 6.0.6 on 2026-08-18 02:41

import core.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_testimonialvideo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="testimonialvideo",
            name="video",
            field=models.FileField(
                storage=core.storage.CloudinaryVideoStorage(),
                upload_to="testimonial-videos/",
            ),
        ),
    ]
