# Generated by Django 6.0.6 on 2026-06-08 08:07

from decimal import Decimal
<<<<<<< HEAD

=======
>>>>>>> 5815f15 (Initial project commit)
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        (
            "invoices",
            "0002_invoice_paid_at_invoice_stripe_checkout_session_id_and_more",
        ),
=======
        ('invoices', '0002_invoice_paid_at_invoice_stripe_checkout_session_id_and_more'),
>>>>>>> 5815f15 (Initial project commit)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="invoice",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0.00"), max_digits=10
            ),
=======
            model_name='invoice',
            name='discount_amount',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
>>>>>>> 5815f15 (Initial project commit)
        ),
    ]
