# Generated by Django 6.0.6 on 2026-08-29 11:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visitor_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("first_seen", models.DateTimeField(auto_now_add=True)),
                ("last_seen", models.DateTimeField(auto_now=True)),
                ("total_sessions", models.PositiveIntegerField(default=0)),
                ("total_page_views", models.PositiveIntegerField(default=0)),
                ("is_returning", models.BooleanField(default=False)),
                (
                    "device_type",
                    models.CharField(blank=True, default="", max_length=30),
                ),
                ("browser", models.CharField(blank=True, default="", max_length=100)),
                (
                    "operating_system",
                    models.CharField(blank=True, default="", max_length=100),
                ),
            ],
        ),
        migrations.CreateModel(
            name="VisitorSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                ("started_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                (
                    "landing_page",
                    models.CharField(blank=True, default="", max_length=500),
                ),
                ("exit_page", models.CharField(blank=True, default="", max_length=500)),
                ("referrer", models.URLField(blank=True, default="", max_length=1000)),
                (
                    "utm_source",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "utm_medium",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "utm_campaign",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sessions",
                        to="analytics.visitor",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SearchEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("query", models.CharField(db_index=True, max_length=500)),
                ("page_url", models.CharField(blank=True, default="", max_length=1000)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="analytics.visitor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="searches",
                        to="analytics.visitorsession",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ActivityEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "event_type",
                    models.CharField(
                        choices=[
                            ("PAGE_VIEW", "Page View"),
                            ("CLICK", "Click"),
                            ("SEARCH", "Search"),
                            ("FORM_START", "Form Start"),
                            ("FORM_SUBMIT", "Form Submit"),
                            ("PHONE_CLICK", "Phone Click"),
                            ("EMAIL_CLICK", "Email Click"),
                            ("QUOTE_START", "Quote Start"),
                            ("QUOTE_SUBMIT", "Quote Submit"),
                            ("BOOKING_START", "Booking Start"),
                            ("BOOKING_COMPLETE", "Booking Complete"),
                            ("FAQ_OPEN", "FAQ Open"),
                            ("DOWNLOAD", "Download"),
                            ("VIDEO_PLAY", "Video Play"),
                            ("GALLERY_VIEW", "Gallery View"),
                            ("CTA_CLICK", "CTA Click"),
                        ],
                        db_index=True,
                        max_length=50,
                    ),
                ),
                ("page_url", models.CharField(blank=True, default="", max_length=1000)),
                ("element", models.CharField(blank=True, default="", max_length=500)),
                ("metadata", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                (
                    "visitor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="analytics.visitor",
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="activities",
                        to="analytics.visitorsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
