# Generated by Django 6.0.6 on 2026-09-04 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("analytics", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="activityevent",
            name="event_type",
            field=models.CharField(
                choices=[
                    ("PAGE_VIEW", "Page View"),
                    ("CLICK", "Click"),
                    ("SEARCH", "Search"),
                    ("FORM_START", "Form Start"),
                    ("FORM_SUBMIT", "Form Submit"),
                    ("PHONE_CLICK", "Phone Click"),
                    ("EMAIL_CLICK", "Email Click"),
                    ("QUOTE_START", "Quote Start"),
                    ("QUOTE_SUBMIT", "Quote Submit"),
                    ("BOOKING_START", "Booking Start"),
                    ("BOOKING_COMPLETE", "Booking Complete"),
                    ("FAQ_OPEN", "FAQ Open"),
                    ("DOWNLOAD", "Download"),
                    ("VIDEO_PLAY", "Video Play"),
                    ("GALLERY_VIEW", "Gallery View"),
                    ("CTA_CLICK", "CTA Click"),
                    ("SCROLL_DEPTH", "Scroll Depth"),
                    ("TIME_ON_PAGE", "Time on Page"),
                    ("PAGE_ENGAGEMENT", "Page Engagement"),
                ],
                db_index=True,
                max_length=50,
            ),
        ),
    ]
