# Generated by Django 6.0.6 on 2026-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0003_consolidate_job_photo_gallery_items"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="after_image",
            field=models.FileField(blank=True, null=True, upload_to="gallery/after/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="before_image",
            field=models.FileField(blank=True, null=True, upload_to="gallery/before/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.FileField(blank=True, null=True, upload_to="gallery/uploads/"),
        ),
    ]
