# Generated by Django 6.0.6 on 2026-07-24 03:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_jobphoto_image"),
        ("gallery", "0004_alter_galleryitem_after_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="job_photo",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="gallery_items",
                to="bookings.jobphoto",
            ),
        ),
    ]
