# Generated by Django 6.0.6 on 2026-07-25 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0005_alter_galleryitem_job_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="after_image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/after/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="before_image",
            field=models.ImageField(blank=True, null=True, upload_to="gallery/before/"),
        ),
        migrations.AlterField(
            model_name="galleryitem",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="gallery/uploads/"
            ),
        ),
    ]
