# Generated by Django 6.0.6 on 2026-07-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0006_alter_galleryitem_after_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="video_platform",
            field=models.CharField(
                blank=True,
                choices=[
                    ("youtube", "YouTube"),
                    ("tiktok", "TikTok"),
                    ("instagram", "Instagram"),
                    ("facebook", "Facebook"),
                ],
                max_length=20,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Paste YouTube, TikTok, Instagram Reel, or Facebook video URL",
                null=True,
            ),
        ),
    ]
