# Generated by Django 6.0.6 on 2026-07-29 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0007_galleryitem_video_platform_galleryitem_video_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="galleryitem",
            name="content_type",
            field=models.CharField(
                choices=[
                    ("image", "Image"),
                    ("before_after", "Before & After"),
                    ("video", "Social Video"),
                ],
                default="image",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="galleryitem",
            name="video_thumbnail",
            field=models.ImageField(
                blank=True,
                help_text="Optional thumbnail image for video preview",
                null=True,
                upload_to="gallery/video_thumbnails/",
            ),
        ),
    ]
