# Generated by Django 6.0.6 on 2026-07-29 04:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0009_gallerymedia"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="galleryitem",
            name="content_type",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="video_platform",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="video_thumbnail",
        ),
        migrations.RemoveField(
            model_name="galleryitem",
            name="video_url",
        ),
        migrations.DeleteModel(
            name="GalleryMedia",
        ),
    ]
