# Generated by Django 6.0.6 on 2026-07-29 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0010_remove_galleryitem_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="galleryitem",
            name="service_type",
            field=models.CharField(
                choices=[
                    ("Commercial Cleaning", "Commercial Cleaning"),
                    ("Office Cleaning", "Office Cleaning"),
                    ("House Cleaning", "House Cleaning"),
                    ("Regular Cleaning", "Regular Cleaning"),
                    ("End of Lease Cleaning", "End of Lease Cleaning"),
                    ("Bond Cleaning", "Bond Cleaning"),
                    ("Deep Cleaning", "Deep Cleaning"),
                    ("Bathroom Deep Cleaning", "Bathroom Deep Cleaning"),
                    ("Kitchen Deep Cleaning", "Kitchen Deep Cleaning"),
                    ("Carpet Steam Cleaning", "Carpet Steam Cleaning"),
                    ("Window & Glass Cleaning", "Window & Glass Cleaning"),
                    ("Oven Cleaning", "Oven Cleaning"),
                    ("Post Construction Cleaning", "Post Construction Cleaning"),
                    ("Builders Cleaning", "Builders Cleaning"),
                    ("Pressure Washing", "Pressure Washing"),
                    ("Retail Cleaning", "Retail Cleaning"),
                    ("Warehouse Cleaning", "Warehouse Cleaning"),
                    ("School & Childcare Cleaning", "School & Childcare Cleaning"),
                    ("Medical Cleaning", "Medical Cleaning"),
                ],
                max_length=100,
            ),
        ),
    ]
