# Generated by Django 6.0.6 on 2026-08-26 14:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0011_alter_galleryitem_service_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "media_type",
                    models.CharField(
                        choices=[("image", "Image"), ("video", "Video")],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/media/images/"
                    ),
                ),
                (
                    "video_platform",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("youtube", "YouTube"),
                            ("tiktok", "TikTok"),
                            ("instagram", "Instagram"),
                            ("facebook", "Facebook"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                ("video_url", models.URLField(blank=True, null=True)),
                (
                    "video_thumbnail",
                    models.ImageField(
                        blank=True, null=True, upload_to="gallery/media/thumbnails/"
                    ),
                ),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media_files",
                        to="gallery.galleryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at"],
            },
        ),
    ]
