# Generated by Django 6.0.6 on 2026-09-04 05:43

import django.db.models.deletion
from django.db import migrations, models


def copy_legacy_gallery_images(apps, schema_editor):
    GalleryImage = apps.get_model("gallery", "GalleryImage")
    GalleryMedia = apps.get_model("gallery", "GalleryMedia")

    for media in GalleryMedia.objects.filter(media_type="image").exclude(image=""):
        GalleryImage.objects.get_or_create(
            gallery_id=media.gallery_id,
            image=media.image,
            defaults={"order": media.order},
        )


class Migration(migrations.Migration):

    dependencies = [
        ("gallery", "0012_gallerymedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="GalleryImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="gallery/multiple/")),
                ("order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "gallery",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="additional_images",
                        to="gallery.galleryitem",
                    ),
                ),
            ],
            options={
                "ordering": ["order", "created_at", "id"],
            },
        ),
        migrations.RunPython(
            copy_legacy_gallery_images,
            migrations.RunPython.noop,
        ),
        migrations.DeleteModel(
            name="GalleryMedia",
        ),
    ]
