# Generated by Django 6.0.6 on 2026-06-24 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_reviews", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.CharField(max_length=255, unique=True)),
                ("reviewer_name", models.CharField(max_length=255)),
                ("reviewer_photo", models.URLField(blank=True)),
                ("rating", models.IntegerField()),
                ("comment", models.TextField()),
                ("review_date", models.DateTimeField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
