# Generated by Django 6.0.6 on 2026-06-24 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_reviews", "0002_googlereview"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleReviewStats",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("average_rating", models.FloatField(default=0)),
                ("total_reviews", models.IntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
