# Generated by Django 6.0.6 on 2026-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("google_reviews", "0003_googlereviewstats"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GoogleReview",
        ),
        migrations.DeleteModel(
            name="GoogleReviewStats",
        ),
    ]
