# Generated by Django 6.0.6 on 2026-07-27 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("google_reviews", "0004_delete_googlereview_delete_googlereviewstats"),
    ]

    operations = [
        migrations.CreateModel(
            name="GoogleReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("review_id", models.CharField(max_length=255, unique=True)),
                ("reviewer_name", models.CharField(blank=True, max_length=255)),
                ("reviewer_photo", models.URLField(blank=True, null=True)),
                ("rating", models.CharField(blank=True, max_length=20)),
                ("comment", models.TextField(blank=True)),
                ("review_date", models.DateTimeField(blank=True, null=True)),
                ("reply", models.TextField(blank=True)),
                ("reply_date", models.DateTimeField(blank=True, null=True)),
                ("review_url", models.URLField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
