# Generated by Django 6.0.6 on 2026-09-09 10:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CorporateLead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "lead_type",
                    models.CharField(
                        choices=[
                            ("proposal", "Corporate Proposal"),
                            ("team_contact", "Speak With Our Team"),
                            ("multi_site", "Multi-Site Cleaning"),
                        ],
                        db_index=True,
                        max_length=30,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("qualified", "Qualified"),
                            ("proposal_sent", "Proposal Sent"),
                            ("negotiating", "Negotiating"),
                            ("won", "Won"),
                            ("lost", "Lost"),
                            ("on_hold", "On Hold"),
                        ],
                        db_index=True,
                        default="new",
                        max_length=30,
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("job_title", models.CharField(blank=True, max_length=150)),
                ("company_name", models.CharField(blank=True, max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                (
                    "industry",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("corporate_office", "Corporate Office"),
                            ("property_management", "Property Management"),
                            ("retail", "Retail"),
                            ("healthcare", "Healthcare"),
                            ("education", "Education"),
                            ("hospitality", "Hospitality"),
                            ("industrial", "Industrial"),
                            ("construction", "Construction"),
                            ("government", "Government"),
                            ("warehouse", "Warehouse / Logistics"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("number_of_sites", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "service_locations",
                    models.TextField(
                        blank=True,
                        help_text="Suburbs, cities or locations requiring service.",
                    ),
                ),
                (
                    "facility_size",
                    models.CharField(
                        blank=True,
                        help_text="Approximate building/facility size.",
                        max_length=150,
                    ),
                ),
                (
                    "services_required",
                    models.TextField(
                        blank=True,
                        help_text="Cleaning services requested by the customer.",
                    ),
                ),
                (
                    "frequency",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("daily", "Daily"),
                            ("multiple_weekly", "Multiple times per week"),
                            ("weekly", "Weekly"),
                            ("fortnightly", "Fortnightly"),
                            ("monthly", "Monthly"),
                            ("one_off", "One-off"),
                            ("custom", "Custom / Flexible"),
                        ],
                        max_length=40,
                    ),
                ),
                ("preferred_start_date", models.DateField(blank=True, null=True)),
                (
                    "current_cleaning_provider",
                    models.CharField(blank=True, max_length=200),
                ),
                (
                    "location_coverage",
                    models.TextField(
                        blank=True,
                        help_text="Details about locations and geographic coverage.",
                    ),
                ),
                ("centralised_invoicing", models.BooleanField(default=False)),
                ("reporting_requirements", models.TextField(blank=True)),
                ("access_requirements", models.TextField(blank=True)),
                ("message", models.TextField(blank=True)),
                (
                    "lead_source",
                    models.CharField(
                        blank=True, default="corporate_page", max_length=100
                    ),
                ),
                ("landing_page", models.URLField(blank=True, max_length=500)),
                ("referrer", models.URLField(blank=True, max_length=500)),
                ("internal_notes", models.TextField(blank=True)),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("consent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_corporate_leads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Corporate Lead",
                "verbose_name_plural": "Corporate Leads",
                "ordering": ["-created_at"],
            },
        ),
    ]
