# Generated by Django 6.0.6 on 2026-06-07 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("leave_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="leaverequest",
            options={"ordering": ["-created_at"]},
        ),
        migrations.AddField(
            model_name="leaverequest",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("annual", "Annual Leave"),
                    ("sick", "Sick Leave"),
                    ("personal", "Personal Leave"),
                    ("unpaid", "Unpaid Leave"),
                ],
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="leaverequest",
            name="reason",
            field=models.TextField(blank=True),
        ),
    ]
