# Generated by Django 6.0.6 on 2026-08-04 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="faqs",
            field=models.JSONField(
                blank=True, default=list, help_text="Frequently asked questions"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="ideal_for",
            field=models.JSONField(
                blank=True, default=list, help_text="Who this service is suitable for"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="industries",
            field=models.JSONField(
                blank=True, default=list, help_text="Industries served"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="introduction",
            field=models.TextField(
                blank=True, help_text="SEO introduction content for service pages"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="problems",
            field=models.JSONField(
                blank=True, default=list, help_text="Common problems solved"
            ),
        ),
        migrations.AddField(
            model_name="service",
            name="process",
            field=models.JSONField(
                blank=True, default=list, help_text="Cleaning process steps"
            ),
        ),
    ]
