# Generated by Django 6.0.6 on 2026-06-10 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0010_vehicle"),
    ]

    operations = [
        migrations.CreateModel(
            name="MaintenanceHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "asset_type",
                    models.CharField(
                        choices=[("vehicle", "Vehicle"), ("equipment", "Equipment")],
                        max_length=20,
                    ),
                ),
                ("asset_name", models.CharField(max_length=200)),
                ("maintenance_date", models.DateField()),
                ("next_service_date", models.DateField(blank=True, null=True)),
                (
                    "cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("performed_by", models.CharField(blank=True, max_length=200)),
                ("description", models.TextField()),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
