# Generated by Django 6.0.6 on 2026-06-15 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0011_maintenancehistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="email_type",
            field=models.CharField(
                choices=[
                    ("invoice_reminder", "Invoice Reminder"),
                    ("booking_reminder", "Booking Reminder"),
                    ("quote_followup", "Quote Follow-up"),
                    ("contract_renewal", "Contract Renewal"),
                    ("system", "System"),
                ],
                default="system",
                max_length=50,
            ),
        ),
    ]
