# Generated by Django 6.0.6 on 2026-07-15 03:35

import dashboard.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0013_alter_emaillog_email_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="SiteImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("hero", "Hero / Homepage"),
                            ("blog", "Blog Post"),
                            ("service", "Service Page"),
                            ("company", "Company / Logo"),
                            ("team", "Team / Staff"),
                            ("other", "Other"),
                        ],
                        default="other",
                        max_length=50,
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        storage=django.core.files.storage.FileSystemStorage(
                            location="/Users/yogendradhami/Desktop/yd-cleaning/static"
                        ),
                        upload_to=dashboard.models.site_image_upload_path,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
