# Generated by Django 6.0.6 on 2026-07-18 09:06

import dashboard.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0014_siteimage"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareerApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=200)),
                ("email", models.EmailField(max_length=254)),
                ("phone", models.CharField(blank=True, max_length=50)),
                ("cover_letter", models.TextField(blank=True)),
                (
                    "resume",
                    models.FileField(
                        blank=True, null=True, upload_to="careers/resumes/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="siteimage",
            name="alt_text",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name="siteimage",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name="siteimage",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="siteimage",
            name="image",
            field=models.ImageField(upload_to=dashboard.models.site_image_upload_path),
        ),
    ]
