# Generated by Django 6.0.6 on 2026-08-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0015_careerapplication_siteimage_alt_text_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='careerapplication',
            name='address',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='admin_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='availability_days',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='availability_hours',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='employment_type',
            field=models.CharField(blank=True, choices=[('casual', 'Casual'), ('part_time', 'Part-time'), ('full_time', 'Full-time'), ('contractor', 'Contractor')], max_length=20),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='has_drivers_license',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='has_vehicle',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='position',
            field=models.CharField(choices=[('residential_cleaner', 'Residential Cleaner'), ('commercial_cleaner', 'Commercial Cleaner'), ('specialist_cleaner', 'Specialist Cleaner'), ('team_leader', 'Cleaning Team Leader'), ('general_application', 'General Application')], default='general_application', max_length=40),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='preferred_start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='previous_cleaning_experience',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='reference_name',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='reference_phone',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='reference_relationship',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='skills',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('reviewing', 'Reviewing'), ('shortlisted', 'Shortlisted'), ('interview', 'Interview'), ('hired', 'Hired'), ('rejected', 'Rejected')], default='new', max_length=20),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='suburb',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='work_rights',
            field=models.CharField(blank=True, choices=[('citizen', 'Australian Citizen'), ('permanent_resident', 'Permanent Resident'), ('visa_holder', 'Visa Holder'), ('other', 'Other')], max_length=30),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='work_rights_details',
            field=models.CharField(blank=True, max_length=250),
        ),
        migrations.AddField(
            model_name='careerapplication',
            name='years_cleaning_experience',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
