# Generated by Django 6.0.6 on 2026-08-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ChatEnquiry",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=150)),
                ("phone", models.CharField(blank=True, max_length=30)),
                ("email", models.EmailField(blank=True, max_length=254)),
                (
                    "enquiry_type",
                    models.CharField(
                        choices=[
                            ("quote", "Get a Quote"),
                            ("booking", "Book a Cleaning"),
                            ("service", "Service Question"),
                            ("general", "General Question"),
                        ],
                        default="general",
                        max_length=20,
                    ),
                ),
                ("service", models.CharField(blank=True, max_length=150)),
                ("suburb", models.CharField(blank=True, max_length=100)),
                ("preferred_date", models.DateField(blank=True, null=True)),
                ("message", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("contacted", "Contacted"),
                            ("resolved", "Resolved"),
                        ],
                        default="new",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Chat Enquiry",
                "verbose_name_plural": "Chat Enquiries",
                "ordering": ["-created_at"],
            },
        ),
    ]
