# Generated by Django 6.0.6 on 2026-09-05 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0005_supportticketreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='livechatconversation',
            name='conversation_state',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='livechatconversation',
            name='intent',
            field=models.CharField(choices=[('general_question', 'General Question'), ('service_enquiry', 'Service Enquiry'), ('pricing_enquiry', 'Pricing Enquiry'), ('quote_request', 'Quote Request'), ('booking_enquiry', 'Booking Enquiry'), ('existing_booking', 'Existing Booking'), ('complaint', 'Complaint'), ('invoice_question', 'Invoice Question'), ('payment_question', 'Payment Question'), ('human_agent', 'Human Agent'), ('other', 'Other'), ('unknown', 'Unknown')], default='unknown', max_length=30),
        ),
        migrations.AddField(
            model_name='livechatconversation',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('collecting', 'Collecting'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], default='none', max_length=20),
        ),
        migrations.AddField(
            model_name='livechatconversation',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('waiting_for_human', 'Waiting for Human'), ('human', 'Human'), ('closed', 'Closed')], default='ai', max_length=20),
        ),
        migrations.AddField(
            model_name='livechatconversation',
            name='service',
            field=models.CharField(blank=True, choices=[('commercial_cleaning', 'Commercial Cleaning'), ('office_cleaning', 'Office Cleaning'), ('window_cleaning', 'Window Cleaning'), ('oven_cleaning', 'Oven Cleaning'), ('carpet_cleaning', 'Carpet Cleaning'), ('spring_cleaning', 'Spring Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('end_of_lease_cleaning', 'End of Lease Cleaning'), ('other', 'Other')], default='', max_length=30),
        ),
    ]
