# Generated by Django 6.0.6 on 2026-09-05 00:10

from django.db import migrations, models


def map_existing_modes(apps, schema_editor):
    LiveChatConversation = apps.get_model("support", "LiveChatConversation")
    LiveChatConversation.objects.filter(status="closed").update(mode="closed")
    LiveChatConversation.objects.filter(status="active").update(mode="human")
    LiveChatConversation.objects.filter(status="waiting").update(mode="ai")


class Migration(migrations.Migration):

    dependencies = [
        ('support', '0006_livechatconversation_conversation_state_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livechatconversation',
            name='intent',
            field=models.CharField(choices=[('general_question', 'General Question'), ('service_enquiry', 'Service Enquiry'), ('pricing_enquiry', 'Pricing Enquiry'), ('quote_request', 'Quote Request'), ('booking_enquiry', 'Booking Enquiry'), ('existing_booking', 'Existing Booking'), ('complaint', 'Complaint'), ('invoice_question', 'Invoice Question'), ('payment_question', 'Payment Question'), ('human_agent', 'Human Agent'), ('other', 'Other'), ('unknown', 'Unknown')], db_index=True, default='unknown', max_length=30),
        ),
        migrations.AlterField(
            model_name='livechatconversation',
            name='lead_status',
            field=models.CharField(choices=[('none', 'None'), ('collecting', 'Collecting'), ('qualified', 'Qualified'), ('converted', 'Converted'), ('lost', 'Lost')], db_index=True, default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='livechatconversation',
            name='mode',
            field=models.CharField(choices=[('ai', 'AI'), ('waiting_for_human', 'Waiting for Human'), ('human', 'Human'), ('closed', 'Closed')], db_index=True, default='ai', max_length=30),
        ),
        migrations.AlterField(
            model_name='livechatconversation',
            name='service',
            field=models.CharField(blank=True, choices=[('commercial_cleaning', 'Commercial Cleaning'), ('office_cleaning', 'Office Cleaning'), ('window_cleaning', 'Window Cleaning'), ('oven_cleaning', 'Oven Cleaning'), ('carpet_cleaning', 'Carpet Cleaning'), ('spring_cleaning', 'Spring Cleaning'), ('deep_cleaning', 'Deep Cleaning'), ('end_of_lease_cleaning', 'End of Lease Cleaning'), ('other', 'Other')], max_length=40),
        ),
        migrations.RunPython(map_existing_modes, migrations.RunPython.noop),
    ]
