# Generated by Django 6.0.6 on 2026-07-18 09:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True, null=True, upload_to=blog.models.blog_upload_path
            ),
        ),
    ]
