# Generated by Django 6.0.6 on 2026-07-26 01:06

import blog.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_blogpost_featured_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="blogpost",
            name="featured_image",
            field=models.ImageField(
                blank=True,
                max_length=500,
                null=True,
                upload_to=blog.models.blog_upload_path,
            ),
        ),
    ]
