# Generated by Django 6.0.6 on 2026-08-24 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rosters", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="roster",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
