# Generated by Django 6.0.6 on 2026-06-09 05:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("bookings", "0005_jobphoto_google_calendar_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CleaningReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pdf_file",
                    models.FileField(
                        blank=True, null=True, upload_to="cleaning_reports/"
                    ),
                ),
                ("emailed_to_customer", models.BooleanField(default=False)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cleaning_report",
                        to="bookings.booking",
                    ),
                ),
            ],
        ),
    ]
