# Generated by Django 6.0.6 on 2026-10-05 09:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_documents", "0001_initial"),
        ("contracts", "0002_cleaningcontract_renewal_14_sent_and_more"),
        ("customers", "0006_marketingsubscriber"),
        ("dashboard", "0016_careerapplication_address_and_more"),
        ("employees", "0005_employee_image"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="companydocument",
            name="related_content_type",
        ),
        migrations.RemoveField(
            model_name="companydocument",
            name="related_object_id",
        ),
        migrations.AddField(
            model_name="companydocument",
            name="contract",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_documents",
                to="contracts.cleaningcontract",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="customer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_documents",
                to="customers.customer",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_documents",
                to="employees.employee",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="related_type",
            field=models.CharField(
                choices=[
                    ("company", "Company"),
                    ("employee", "Employee"),
                    ("customer", "Customer"),
                    ("vehicle", "Vehicle"),
                    ("supplier", "Supplier"),
                    ("contract", "Contract"),
                ],
                db_index=True,
                default="company",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="supplier",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_documents",
                to="dashboard.supplier",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="vehicle",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="company_documents",
                to="dashboard.vehicle",
            ),
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="name",
            field=models.CharField(db_index=True, max_length=255),
        ),
    ]
