# Generated by Django 6.0.6 on 2026-10-05 09:20

import company_documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "company_documents",
            "0002_remove_companydocument_related_content_type_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="companydocument",
            name="file",
            field=models.FileField(
                max_length=500,
                storage=company_documents.storage.CompanyDocumentStorage(),
                upload_to="company_documents/%Y/%m/",
            ),
        ),
        migrations.AlterField(
            model_name="companydocument",
            name="mime_type",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
