# Generated by Django 6.0.6 on 2026-10-05 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_documents", "0003_alter_companydocument_file_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BulkImportBatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "batch_reference",
                    models.CharField(db_index=True, max_length=40, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("analysing", "Analysing"),
                            ("review", "Review Required"),
                            ("importing", "Importing"),
                            ("completed", "Completed"),
                            ("partial", "Partially Completed"),
                            ("failed", "Failed"),
                            ("cancelled", "Cancelled"),
                        ],
                        db_index=True,
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                ("total_files", models.PositiveIntegerField(default=0)),
                ("processed_files", models.PositiveIntegerField(default=0)),
                ("approved_files", models.PositiveIntegerField(default=0)),
                ("imported_files", models.PositiveIntegerField(default=0)),
                ("review_required", models.PositiveIntegerField(default=0)),
                ("duplicate_count", models.PositiveIntegerField(default=0)),
                ("failed_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="company_document_import_batches",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Bulk document import",
                "verbose_name_plural": "Bulk document imports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="BulkImportItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("original_filename", models.CharField(max_length=500)),
                ("file_size", models.PositiveBigIntegerField(default=0)),
                ("mime_type", models.CharField(blank=True, max_length=255)),
                (
                    "file_hash",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("analysing", "Analysing"),
                            ("ready", "Ready"),
                            ("review", "Review Required"),
                            ("approved", "Approved"),
                            ("imported", "Imported"),
                            ("duplicate", "Duplicate"),
                            ("failed", "Failed"),
                            ("skipped", "Skipped"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("extracted_text", models.TextField(blank=True)),
                ("extraction_method", models.CharField(blank=True, max_length=50)),
                ("extraction_error", models.TextField(blank=True)),
                ("suggested_name", models.CharField(blank=True, max_length=255)),
                ("suggested_category", models.CharField(blank=True, max_length=50)),
                (
                    "suggested_document_type",
                    models.CharField(blank=True, max_length=255),
                ),
                ("suggested_description", models.TextField(blank=True)),
                ("suggested_reference", models.CharField(blank=True, max_length=255)),
                ("suggested_version", models.CharField(blank=True, max_length=50)),
                ("suggested_related_type", models.CharField(blank=True, max_length=50)),
                (
                    "suggested_employee_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "suggested_customer_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "suggested_vehicle_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "suggested_supplier_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "suggested_contract_id",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                ("suggested_issue_date", models.DateField(blank=True, null=True)),
                ("suggested_expiry_date", models.DateField(blank=True, null=True)),
                ("suggested_review_date", models.DateField(blank=True, null=True)),
                ("suggested_sensitive", models.BooleanField(default=False)),
                ("confidence_score", models.PositiveSmallIntegerField(default=0)),
                ("confidence_label", models.CharField(blank=True, max_length=30)),
                ("classification_reasons", models.JSONField(blank=True, default=list)),
                ("extracted_fields", models.JSONField(blank=True, default=dict)),
                (
                    "duplicate_score",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("reviewer_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("analysed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("imported_at", models.DateTimeField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="company_documents.bulkimportbatch",
                    ),
                ),
                (
                    "duplicate_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_duplicate_candidates",
                        to="company_documents.companydocument",
                    ),
                ),
                (
                    "imported_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="bulk_import_source_items",
                        to="company_documents.companydocument",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_company_document_import_items",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
                "indexes": [
                    models.Index(
                        fields=["batch", "status"],
                        name="company_doc_batch_i_fe519f_idx",
                    ),
                    models.Index(
                        fields=["file_hash"], name="company_doc_file_ha_96612b_idx"
                    ),
                    models.Index(
                        fields=["confidence_score"],
                        name="company_doc_confide_417a1e_idx",
                    ),
                ],
            },
        ),
    ]
