# Generated by Django 6.0.6 on 2026-10-05 12:39

import company_documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_documents", "0004_bulkimportbatch_bulkimportitem"),
    ]

    operations = [
        migrations.AddField(
            model_name="bulkimportitem",
            name="staging_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=company_documents.storage.CompanyDocumentStorage(),
                upload_to="company_document_import_staging/%Y/%m/",
            ),
        ),
        migrations.AddField(
            model_name="companydocument",
            name="file_hash",
            field=models.CharField(
                blank=True,
                db_index=True,
                help_text="SHA-256 hash of the uploaded file.",
                max_length=64,
            ),
        ),
    ]
