# Generated by Django 6.0.6 on 2026-10-05 13:02

import company_documents.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_documents", "0005_bulkimportitem_staging_file_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bulkimportitem",
            name="staging_file",
            field=models.FileField(
                blank=True,
                max_length=500,
                null=True,
                storage=company_documents.storage.CompanyDocumentStorage(),
                upload_to="company_document_staging/%Y/%m/",
            ),
        ),
    ]
