# Generated by Django 6.0.6 on 2026-10-06 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("company_documents", "0006_alter_bulkimportitem_staging_file"),
    ]

    operations = [
        migrations.CreateModel(
            name="ComplianceRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=180)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("company", "Company"),
                            ("employee", "Employee"),
                            ("customer", "Customer"),
                            ("vehicle", "Vehicle"),
                            ("supplier", "Supplier"),
                            ("contract", "Contract"),
                        ],
                        max_length=30,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CompanyDocument category used when matching existing documents.",
                        max_length=50,
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="CompanyDocument document type used for matching.",
                        max_length=180,
                    ),
                ),
                ("description", models.TextField(blank=True, default="")),
                ("required", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("sensitive", models.BooleanField(default=False)),
                ("sort_order", models.PositiveIntegerField(default=100)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["scope", "sort_order", "name"],
                "indexes": [
                    models.Index(
                        fields=["scope", "active"], name="company_doc_scope_83128f_idx"
                    ),
                    models.Index(
                        fields=["category", "document_type"],
                        name="company_doc_categor_e38641_idx",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("scope", "name"),
                        name="unique_compliance_requirement_scope_name",
                    )
                ],
            },
        ),
    ]
