# Generated by Django 6.0.6 on 2026-06-05 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("customers", "0001_initial"),
=======
        ('customers', '0001_initial'),
>>>>>>> 5815f15 (Initial project commit)
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="customer",
            name="user",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="customer_profile",
                to=settings.AUTH_USER_MODEL,
            ),
=======
            model_name='customer',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='customer_profile', to=settings.AUTH_USER_MODEL),
>>>>>>> 5815f15 (Initial project commit)
        ),
    ]
