# Generated by Django 6.0.6 on 2026-06-23 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0002_customer_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="customer",
            name="email_verified",
            field=models.BooleanField(
                default=False, help_text="Has customer verified email address?"
            ),
        ),
        migrations.AddField(
            model_name="customer",
            name="verification_token",
            field=models.CharField(
                blank=True,
                help_text="Email verification token",
                max_length=255,
                null=True,
            ),
        ),
    ]
