# Generated by Django 6.0.6 on 2026-07-18 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0003_customer_email_verified_customer_verification_token"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customer",
            name="email_verified",
        ),
        migrations.RemoveField(
            model_name="customer",
            name="verification_token",
        ),
    ]
