# Generated by Django 6.0.6 on 2026-09-11 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0005_customer_email_verified_customer_verification_token"),
    ]

    operations = [
        migrations.CreateModel(
            name="MarketingSubscriber",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "consent_given",
                    models.BooleanField(
                        default=False,
                        help_text="Has the subscriber explicitly agreed to receive promotional emails?",
                    ),
                ),
                ("consented_at", models.DateTimeField(blank=True, null=True)),
                (
                    "source",
                    models.CharField(default="homepage_clean20", max_length=100),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
