# Generated by Django 6.0.6 on 2026-10-04 09:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("employees", "0005_employee_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="InductionModule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=80, unique=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("welcome", "Welcome & Company"),
                            ("whs", "WHS & Safety"),
                            ("operations", "Cleaning Operations"),
                            ("conduct", "Conduct & Privacy"),
                            ("role", "Role Specific"),
                        ],
                        default="whs",
                        max_length=30,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all", "All Employees"),
                            ("cleaner", "Cleaner"),
                            ("supervisor", "Supervisor"),
                            ("manager", "Manager"),
                        ],
                        default="all",
                        max_length=30,
                    ),
                ),
                ("summary", models.CharField(blank=True, max_length=300)),
                ("content", models.TextField()),
                (
                    "acknowledgement_text",
                    models.CharField(
                        default="I have read, understood and agree to follow this module.",
                        max_length=300,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=10)),
                ("mandatory", models.BooleanField(default=True)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="InductionProgramme",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        default="YD Commercial Cleaning New Starter Induction",
                        max_length=160,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("description", models.TextField(blank=True)),
                ("active", models.BooleanField(default=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-active", "-version"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeInduction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("assigned", "Assigned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="assigned",
                        max_length=20,
                    ),
                ),
                (
                    "employment_type",
                    models.CharField(
                        choices=[
                            ("casual", "Casual"),
                            ("part_time", "Part-time"),
                            ("full_time", "Full-time"),
                            ("contractor", "Contractor"),
                        ],
                        default="casual",
                        max_length=20,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("supervisor_name", models.CharField(blank=True, max_length=150)),
                ("primary_work_location", models.CharField(blank=True, max_length=255)),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("induction_duration_minutes", models.PositiveIntegerField(default=60)),
                ("declaration_name", models.CharField(blank=True, max_length=150)),
                ("declaration_at", models.DateTimeField(blank=True, null=True)),
                ("declaration_ip", models.GenericIPAddressField(blank=True, null=True)),
                ("declaration_user_agent", models.TextField(blank=True)),
                ("notes", models.TextField(blank=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="induction",
                        to="employees.employee",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="inductions",
                        to="induction.inductionprogramme",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InductionModuleCompletion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("module_title_snapshot", models.CharField(max_length=180)),
                ("module_version", models.PositiveIntegerField(default=1)),
                ("completed_at", models.DateTimeField(auto_now_add=True)),
                ("acknowledgement", models.BooleanField(default=True)),
                ("acknowledgement_text", models.CharField(max_length=300)),
                ("notes", models.TextField(blank=True)),
                (
                    "induction",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="completions",
                        to="induction.employeeinduction",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="completions",
                        to="induction.inductionmodule",
                    ),
                ),
            ],
            options={
                "ordering": ["completed_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("induction", "module"),
                        name="unique_induction_module_completion",
                    )
                ],
            },
        ),
    ]
