# Generated by Django 6.0.6 on 2026-10-04 10:01

import django.db.models.deletion
import induction.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("employees", "0005_employee_image"),
        ("induction", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="OnboardingRequirement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("code", models.SlugField(max_length=100, unique=True)),
                ("title", models.CharField(max_length=180)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("identity", "Identity"),
                            ("employment", "Employment"),
                            ("right_to_work", "Right to Work"),
                            ("compliance", "Compliance"),
                            ("training", "Training"),
                            ("licence", "Licence / Certificate"),
                            ("policy", "Policy"),
                            ("other", "Other"),
                        ],
                        default="employment",
                        max_length=30,
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("all", "All Employees"),
                            ("cleaner", "Cleaner"),
                            ("supervisor", "Supervisor"),
                            ("manager", "Manager"),
                        ],
                        default="all",
                        max_length=30,
                    ),
                ),
                ("description", models.TextField(blank=True)),
                ("required", models.BooleanField(default=True)),
                ("employee_upload_allowed", models.BooleanField(default=True)),
                (
                    "expiry_days",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Number of days until the document expires. Leave blank if it does not expire.",
                        null=True,
                    ),
                ),
                ("version", models.PositiveIntegerField(default=1)),
                ("sort_order", models.PositiveIntegerField(default=10)),
                ("active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeOnboardingProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_documents", "Documents Required"),
                            ("under_review", "Under HR Review"),
                            ("ready", "Ready for Work"),
                            ("blocked", "Blocked"),
                        ],
                        default="pending_documents",
                        max_length=30,
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("ready_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="employee_onboarding_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["status", "-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="EmployeeOnboardingDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=induction.models.onboarding_document_upload_path
                    ),
                ),
                ("original_filename", models.CharField(max_length=255)),
                ("version", models.PositiveIntegerField(default=1)),
                ("is_current", models.BooleanField(default=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending Review"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("review_notes", models.TextField(blank=True)),
                ("expires_at", models.DateField(blank=True, null=True)),
                ("acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("acknowledged_name", models.CharField(blank=True, max_length=150)),
                ("uploaded_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "employee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="onboarding_documents",
                        to="employees.employee",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="onboarding_document_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "requirement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="employee_documents",
                        to="induction.onboardingrequirement",
                    ),
                ),
            ],
            options={
                "ordering": ["-is_current", "-uploaded_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("employee", "requirement", "version"),
                        name="unique_onboarding_document_version",
                    )
                ],
            },
        ),
    ]
