# Generated by Django 6.0.6 on 2026-10-04 10:37

import induction.models
import induction.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("induction", "0002_onboardingrequirement_employeeonboardingprofile_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeonboardingdocument",
            name="file",
            field=models.FileField(
                storage=induction.storage.EmployeeOnboardingDocumentStorage(),
                upload_to=induction.models.onboarding_document_upload_path,
            ),
        ),
    ]
