# Generated by Django 6.0.6 on 2026-10-04 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("induction", "0003_alter_employeeonboardingdocument_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employeeonboardingprofile",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_documents", "Documents Required"),
                    ("under_review", "Under HR Review"),
                    ("compliance_complete", "Compliance Complete"),
                    ("ready", "Ready for Work"),
                    ("blocked", "Blocked"),
                ],
                default="pending_documents",
                max_length=30,
            ),
        ),
    ]
