# Generated by Django 6.0.6 on 2026-06-05 01:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0001_initial"),
        ("employees", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="assigned_cleaner",
        ),
        migrations.AddField(
            model_name="booking",
            name="assigned_employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assigned_bookings",
                to="employees.employee",
            ),
        ),
    ]
