# Generated by Django 6.0.6 on 2026-06-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0005_jobphoto_google_calendar_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobphoto",
            name="google_calendar_event_id",
            field=models.CharField(
                blank=True,
                help_text="Google Calendar Event ID",
                max_length=255,
                null=True,
            ),
        ),
    ]
