# Generated by Django 6.0.6 on 2026-07-18 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0006_alter_jobphoto_google_calendar_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobphoto",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
