# Generated by Django 6.0.6 on 2026-07-24 03:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0007_alter_jobphoto_google_calendar_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobphoto",
            name="image",
            field=models.FileField(upload_to="job_photos/"),
        ),
    ]
