# Generated by Django 6.0.6 on 2026-07-25 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0008_alter_jobphoto_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jobphoto",
            name="image",
            field=models.ImageField(upload_to="job_photos/"),
        ),
    ]
