# Generated by Django 6.0.6 on 2026-08-23 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bookings", "0009_alter_jobphoto_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="google_calendar_event_id",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
