# Generated by Django 6.0.6 on 2026-06-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("quote", "Quote"),
                    ("booking", "Booking"),
                    ("invoice", "Invoice"),
                    ("customer", "Customer"),
                    ("employee", "Employee"),
                    ("gallery", "Gallery"),
                    ("review", "Review"),
                    ("report", "Report"),
                    ("contract", "Contract"),
                    ("attendance", "Attendance"),
                    ("payroll", "Payroll"),
                    ("leave", "Leave"),
                    ("roster", "Roster"),
                    ("system", "System"),
                ],
                default="system",
                max_length=30,
            ),
        ),
    ]
