# Generated by Django 6.0.6 on 2026-06-04 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="suburb",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="service",
            field=models.CharField(
                choices=[
                    ("Commercial Cleaning", "Commercial Cleaning"),
                    ("Office Cleaning", "Office Cleaning"),
                    ("House Cleaning", "House Cleaning"),
                    ("End of Lease Cleaning", "End of Lease Cleaning"),
                    ("Window Cleaning", "Window Cleaning"),
                    ("Deep Cleaning", "Deep Cleaning"),
                    ("Post Construction Cleaning", "Post Construction Cleaning"),
                ],
                max_length=100,
            ),
        ),
    ]
