# Generated by Django 6.0.6 on 2026-06-04 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0003_remove_quoterequest_service_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="quoterequest",
            name="property_type",
            field=models.CharField(
                choices=[
                    ("", "– Select property type –"),
                    ("House", "House"),
                    ("Apartment", "Apartment"),
                    ("Office", "Office"),
                    ("Commercial Property", "Commercial Property"),
                    ("End of Lease Property", "End of Lease Property"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="quoterequest",
            name="suburb_postcode",
            field=models.CharField(max_length=150),
        ),
    ]
