# Generated by Django 6.0.6 on 2026-06-09 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("quotes", "0005_quoterequest_admin_notes_quoterequest_status"),
=======
        ('quotes', '0005_quoterequest_admin_notes_quoterequest_status'),
>>>>>>> 5815f15 (Initial project commit)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="quoterequest",
            name="bathrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="bedrooms",
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name="quoterequest",
            name="estimated_price",
=======
            model_name='quoterequest',
            name='bathrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='bedrooms',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='quoterequest',
            name='estimated_price',
>>>>>>> 5815f15 (Initial project commit)
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
