# Generated by Django 6.0.6 on 2026-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quotes", "0006_quoterequest_bathrooms_quoterequest_bedrooms_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="quoterequest",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("google", "Google Business Profile"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("hipages", "Hipages"),
                    ("referral", "Referral"),
                    ("other", "Other"),
                ],
                default="website",
                max_length=50,
            ),
        ),
    ]
