# Generated by Django 6.0.6 on 2026-06-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("quotes", "0006_quoterequest_bathrooms_quoterequest_bedrooms_and_more"),
=======
        ('quotes', '0006_quoterequest_bathrooms_quoterequest_bedrooms_and_more'),
>>>>>>> 5815f15 (Initial project commit)
    ]

    operations = [
        migrations.AddField(
<<<<<<< HEAD
            model_name="quoterequest",
            name="lead_source",
            field=models.CharField(
                choices=[
                    ("website", "Website"),
                    ("google", "Google Business Profile"),
                    ("facebook", "Facebook"),
                    ("instagram", "Instagram"),
                    ("tiktok", "TikTok"),
                    ("hipages", "Hipages"),
                    ("referral", "Referral"),
                    ("other", "Other"),
                ],
                default="website",
                max_length=50,
            ),
=======
            model_name='quoterequest',
            name='lead_source',
            field=models.CharField(choices=[('website', 'Website'), ('google', 'Google Business Profile'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('hipages', 'Hipages'), ('referral', 'Referral'), ('other', 'Other')], default='website', max_length=50),
>>>>>>> 5815f15 (Initial project commit)
        ),
    ]
