# Generated by Django 6.0.6 on 2026-09-05 00:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0007_quoterequest_lead_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='quoterequest',
            name='idempotency_key',
            field=models.CharField(blank=True, editable=False, max_length=100, null=True, unique=True),
        ),
    ]
